### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by karan** [scleradb/sclera-extensions-scala#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by prasanroy** [comment]
Thanks for the note, Karan.

There is a LICENSE.txt mentioning the applicable license in each directory.

Please note that the code in each directory is an independent extension, with its own set of dependencies, and accordingly has a separate license.
